---
swagger: "2.0"
info:
  description: "JMS Rest API exposes the Java EE back-end to the front-end"
  version: "1.0.0"
  title: "JMS Client APIs"
  contact:
    name: "Rinus Hofman"
    url: "http://localhost:8080"
  license:
    name: "License name"
    url: "http://www.license.com"
host: "localhost:8080"
basePath: "/jmsRestClient/api"
tags:
- name: "Queue"
schemes:
- "http"
- "https"
